include: package:pedantic/analysis_options.yaml

# My though on this is that source code is more self explanatory
# about types of variables then declaring it with var
analyzer:
  errors:
    prefer_collection_literals: ignore
    omit_local_variable_types: ignore

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - collection_methods_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
